### PR TITLE
Update to Cygwin v3.3.6

### PR DESCRIPTION
**Pull request by dscho**
Changelog: https://cygwin.com/git/?p=newlib-cygwin.git;a=blob;f=winsup/cygwin/release/3.3.6

Upstream changes: https://github.com/msys2/msys2-runtime/compare/cygwin-3_3_5-release...cygwin-3_3_6-release

Range-diff:

```console
$ git range-diff cygwin-3_3_5-release..msys2-3_3_5-release cygwin-3_3_6-release..msys2-3_3_6-release-wip
```

* 1:  6ab46fff52 =  1:  1e32c73dcc Add MSYS2 triplet
* 2:  14e3f594d4 =  2:  e78e1440c2 Fix msys library name in import libraries
* 3:  c07794392e =  3:  27982ff1c2 Rename dll from cygwin to msys
* 4:  03929e0952 !  4:  eec753278b Add functionality for converting UNIX paths in arguments and environment variables to Windows form for native Win32 applications.

   ```diff
   @@ winsup/cygwin/msys2_path_conv.cc (new)
    +
    +    if (!prev_was_simc) {
    +        subp_convert(&beg, it, is_url, dst, dstend);
   -+    } else {
   -+        *dst -= 1;
    +    }
    +}
    +
   ```

* 5:  77261f7d78 =  5:  4282d49215 Add functionality for changing OS name via MSYSTEM environment variables.
* 6:  45fd39e78c =  6:  7794a2ab74 - Move root to /usr. - Change sorting mount points. - By default mount without ACLs. - Can read /etc/fstab with short mount point format.
* 7:  0ecbb9c1c8 =  7:  bb01dd41c6 Instead of creating Cygwin symlinks, use deep copy by default
* 8:  f1b4626781 =  8:  6f8d01098e Automatically rewrite TERM=msys to TERM=cygwin With MSys1, it was necessary to set the TERM variable to "msys". To allow for a smooth transition from MSys1 to MSys2, let's simply handle TERM=msys as if the user had not specified TERM at all and wanted us to use our preferred TERM value.
* 9:  f9c5a292e9 =  9:  528620587a Do not convert environment for strace
* 10:  dbc74bed0f = 10:  4676ec44f2 Special case for converting root directory to have training slash
* 11:  8da0f35299 = 11:  afe78f3234 dcrt0.cc: Untangle allow_glob from winshell
* 12:  bb5f409b67 = 12:  8cbda4bfc8 dcrt0.cc (globify): Don't quote literal strings differently when dos_spec
* 13:  e93812d6be = 13:  93909972c2 strace.cc: Don't set MSYS=noglob
* 14:  30759e9f93 = 14:  5a00c6b340 Add debugging for build_argv
* 15:  1c6ba9dff9 = 15:  aaadd11364 Add debugging for strace make_command_line
* 16:  9de4fa8cbf = 16:  9559773cc4 environ.cc: New facility/environment variable MSYS2_ENV_CONV_EXCL
* 17:  210d271d3e = 17:  3578452c55 Fix native symbolic link spawn passing wrong arg0
* 18:  47ea73cc21 = 18:  b0485d48b3 QueryUnbiasedInterruptTime must be load from kernel32.dll
* 19:  099ccbb458 = 19:  09db143dac strace --quiet: be *really* quiet
* 20:  b74f834aa6 = 20:  8e89fffcfb Default to `disable_pcon`
* 21:  76648c9e51 = 21:  a4a2aebc21 Introduce the `enable_pcon` value for `MSYS`
* 22:  1333709d99 = 22:  f9b94aa836 popen: call /usr/bin/sh instead of /bin/sh
* 23:  146f1a7173 = 23:  69029b18df CI: add a GHA for doing a basic build test
* 24:  477d12f0ec = 24:  51766aba40 Set up a GitHub Action to keep in sync with Cygwin
* 25:  b911cd8690 = 25:  b37c67a230 Expose full command-lines to other Win32 processes by default
* 26:  f9fe9e6932 = 26:  991789ad7a Disable the 'cygwin' GitHub workflow
* 27:  d67cd1068d = 27:  c20ec3a443 Do not show Error dialogs by default
* 28:  65fa01a7c8 = 28:  22f77091e9 Add a helper to obtain a function's address in kernel32.dll
* 29:  3ef5043602 = 29:  be43d13309 Emulate GenerateConsoleCtrlEvent() upon Ctrl+C
* 30:  fcf9fbe488 = 30:  486c760150 kill: kill Win32 processes more gently
* 31:  e71dc3c088 = 31:  aa9dbc9c9f Cygwin: make option for native inner link handling.
* 32:  506a54e425 = 32:  20f59b414f docs: skip building texinfo and PDF files
* 33:  91bc72c56c = 33:  31b5e84ef7 install-libs: depend on the "toollibs"
* 34:  8bb4359ac2 = 34:  ae6fceff61 POSIX-ify the SHELL variable
* 35:  991a737788 = 35:  7af6781845 Handle ORIGINAL_PATH just like PATH
* 36:  dceb4cc4c9 <  -:  ---------- fixup! Add functionality for converting UNIX paths in arguments and environment variables to Windows form for native Win32 applications.
* 37:  041f56f61c = 36:  1a5f889bdb uname: allow setting the system name to CYGWIN

### CODE REVIEW

**Comment by dscho** [comment]
> * 4:  [03929e0](https://github.com/msys2/msys2-runtime/commit/03929e0952ba0d460b0348046c9354fcacce0b78) !  4:  [eec7532](https://github.com/msys2/msys2-runtime/commit/eec753278b54a8ad5e5371dfe1b4c3023408fed4) Add functionality for converting UNIX paths in arguments and environment variables to Windows form for native Win32 applications.
>       ```diff
>       @@ winsup/cygwin/msys2_path_conv.cc (new)
>        +
>        +    if (!prev_was_simc) {
>        +        subp_convert(&beg, it, is_url, dst, dstend);
>       -+    } else {
>       -+        *dst -= 1;
>        +    }
>        +}
>        +
>       ```

This change comes from:

> * 36:  [dceb4cc](https://github.com/msys2/msys2-runtime/commit/dceb4cc4c99b77e4fae1f171d6f054c670918c81) <  -:  ---------- fixup! Add functionality for converting UNIX paths in arguments and environment variables to Windows form for native Win32 applications.

**Comment by jeremyd2019** [comment]
Seems odd that 717c36c0a4e387a73146c1181b7b89f091176e85 didn't get backported to 3.3.  Every time I see a hang/deadlock fix I hope it's *my* hang/deadlock on ARM64 that I've never been able to debug (discussed msys2/msys2-autobuild#62)

**Review by lazka — APPROVED** [review]

**Comment by dscho** [comment]
> Seems odd that [717c36c](https://github.com/msys2/msys2-runtime/commit/717c36c0a4e387a73146c1181b7b89f091176e85) didn't get backported to 3.3. Every time I see a hang/deadlock fix I hope it's _my_ hang/deadlock on ARM64 that I've never been able to debug (discussed [msys2/msys2-autobuild#62](https://github.com/msys2/msys2-autobuild/issues/62))

Probably because that is a fix for https://github.com/msys2/msys2-runtime/commit/63b503916d4258cec39df09c545498e463d9a088 which _also_ did not make it to v3.3.x.

In any case, is this comment part of your review of _this_ here PR? 😁

**Comment by dscho** [comment]
@lazka would you mind adjusting the default branch (I would, but I don't have the permission).

**Comment by lazka** [comment]
> @lazka would you mind adjusting the default branch (I would, but I don't have the permission).

you should now

**Comment by dscho** [comment]
> > @lazka would you mind adjusting the default branch (I would, but I don't have the permission).
> 
> you should now

I can, and I did! Thank you!

**Pull request merged**
