### PR TITLE
Fix MSYS=wincmdln, and enable it by default

### PR DESCRIPTION
**Pull request by dscho**
This is apparently broken since 2015...

### CODE REVIEW

**Comment by dscho** [comment]
I marked this up as a `fixup!` so that the next rebase (provided that `git rebase -i` is used, with auto-squash in effect) squashes these changes into the appropriate patch.

FWIW I wonder whether we should also make `wincmdln` the default for MSYS2?

**Comment by lazka** [comment]
If I understand this correctly this is for non-cygwin binaries in which case the path would have been hit anyway because !real_path.iscygexec(). Am I missing something?

(unrelated, as you might have noticed I've changed the default branch for this repo and added CI. I hope that's ok)

**Comment by elieux** [comment]
Based on my debugging experience, missing command line arguments are an issue in cygwin processes, not Win32 ones.

**Comment by elieux** [comment]
Assuming there's no disadvantage to this feature, I would like this turned on by default (or hard-coded even).

**Comment by dscho** [comment]
> If I understand this correctly this is for non-cygwin binaries in which case the path would have been hit anyway because !real_path.iscygexec(). Am I missing something?

No, this is for MSYS2/Cygwin binaries. If you call, say, `vim.exe abc` from a regular MSYS2 Bash, you won't see the command-line arguments in the output of `wmic process where "CommandLine like '%vim%'" get CommandLine` (see https://github.com/git-for-windows/git/issues/2756 for more details).

> Assuming there's no disadvantage to this feature, I would like this turned on by default (or hard-coded even).

There is only _one_ disadvantage that _I_ can see: as the shown command-line is not the _actual_ command-line as used by MSYS2/Cygwin, there might be discrepancies. The most obvious one comes when the command-line is longer than 32k: this is allowed in MSYS2 when calling another MSYS2 process, but it would be shown truncated by `wmic`.

However, I think you're right: this should be the default nevertheless because the surprise of not seeing any command-line arguments is bigger than the surprise of seeing a potentially truncated one.

Having said that, I do want to give users an "escape hatch" in case they absolutely _want_ Cygwin's default behavior, so I am more in favor of just switching the default and support opting out (via `MSYS=nowincmdln`). Sound okay?

**Comment by dscho** [comment]
I just added a commit to enable `MSYS=wincmdln` by default, and verified that it works.

**Comment by elieux** [comment]
> Having said that, I do want to give users an "escape hatch" in case they absolutely _want_ Cygwin's default behavior, so I am more in favor of just switching the default and support opting out (via `MSYS=nowincmdln`). Sound okay?

Okey dokey.

**Comment by dscho** [comment]
@elieux @lazka so... any chance one of you could review these two patches (and approve)?

**Comment by elieux** [comment]
Sure. But did you add that second commit? I can't see it.

**Comment by lazka** [comment]
> No, this is for MSYS2/Cygwin binaries. If you call, say, `vim.exe abc` from a regular MSYS2 Bash, you won't see the command-line arguments in the output of `wmic process where "CommandLine like '%vim%'" get CommandLine` (see [git-for-windows/git#2756](https://github.com/git-for-windows/git/issues/2756) for more details).

ok, I was confused since the commit says "for native Win32 applications". Thanks for the explanation. With my very limited cpp/cygwin experience, your explanation makes sense, so lgtm.

**Comment by dscho** [comment]
>  did you add that second commit? I can't see it.

I had pushed it, but to another remote. D'oh! Sorry ;-)

**Comment by dscho** [comment]
FWIW [this](https://github.com/msys2/Cygwin/pull/10/commits/fae9acdc62656fbf643dccb716d1e21751335386) is the second commit I was talking about.

**Review by lazka — APPROVED** [review]

**Comment by elieux** [comment]
Should the docs be updated or do we not care about them?

**Comment by elieux** [comment]
> ```
> <listitem>
> <para><envar>(no)wincmdln</envar> - if set, the windows complete command
> line (truncated to ~32K) will be passed on any processes that it creates
> in addition to the normal UNIX argv list.  Defaults to not set.</para>
> </listitem>
> ```

**Comment by elieux** [comment]
It is hard for me to follow the code, but comparing our current code and your patched code both to upstream code, yours seems to be more logical. I'm assuming it builds and does what it says on the tin.

**Review by elieux — APPROVED** [review]

**Comment by dscho** [comment]
> Should the docs be updated or do we not care about them?

I was on the fence, as the documentation still talks about `CYGWIN` while we ignore that environment variable and look at `MSYS` instead.

> It is hard for me to follow the code, but comparing our current code and your patched code both to upstream code, yours seems to be more logical.

Basically, [@Alexpux' patch](https://github.com/msys2/Cygwin/commit/91990dabdc3c09d1951325d601593cb31815da7c) erroneously moves the `if (wincmdln ...)` block from being a sibling of the `if (real_path.iscygexec ())` block to an `else` arm of the latter. For details, see https://github.com/msys2/Cygwin/commit/91990dabdc3c09d1951325d601593cb31815da7c#diff-b72d3b2289a1e6410a2602d0fa250a3cL386-L395 (and expand the preceding context a bit).

My patch moves the `if (wincmdln ...)` block _out_ of that `else` arm again, so that it also applies to spawned MSYS2 processes.

> I'm assuming it builds and does what it says on the tin.

Yes, I tested (and just re-tested, to be sure) the built `msys0.dll`, verifying that it does what I claim in this PR.

**Comment by lazka** [comment]
offtopic, would it make sense to rename this repo to msys2-runtime? To make the relation to the package more clear?

**Comment by dscho** [comment]
> offtopic, would it make sense to rename this repo to msys2-runtime? To make the relation to the package more clear?

Sure. In Git for Windows, we did exactly that: https://github.com/git-for-windows/msys2-runtime/

**Comment by lazka** [comment]
:+1: done

**Pull request merged**
