### PR TITLE
Update to cygwin 3.3.1

### LINKED ISSUE #61: Update to cygwin 3.3.x
https://cygwin.com/git/?p=newlib-cygwin.git;a=shortlog;h=refs/heads/cygwin-3_3-branch

https://cygwin.com/pipermail/cygwin-announce/2021-October/010268.html

https://cygwin.com/pipermail/cygwin-announce/2021-October/010269.html

### PR DESCRIPTION
**Pull request by lazka**
WIP -> broken

* [ ] doc build broken (was before I think, we just need to skip pdf/html generation now)
* [ ] install broken (something re libmsys-2.0.a)
* [ ] https://github.com/msys2/msys2-runtime/commit/3839f28dbf2d09b98e6c6f37e7e0e46eb3d97dda#diff-4ede10814d0ef87034153c055aab487583a68313ad9a4a3bd1228945ce23e979 needs to be ported
* [ ] maybe patch cleanup?

Fixes #61

### CODE REVIEW

**Comment by dscho** [comment]
>     * doc build broken (was before I think, we just need to skip pdf/html generation now)

I see that these lines in `winsup/Makefile.in` (which was removed) do not have any equivalent in `winsup/Makefile.am` (which was added), which is the most likely explanation:

```
$(SUBDIRS):
       @${MAKE} -C $@ all || ([ "$@" == doc ] && echo "*** error ignored")
```

I'm on it.

> * install broken (something re libmsys-2.0.a)

I did not see that problem in the workflow runs... Could you share any details?

>     * [3839f28#diff-4ede10814d0ef87034153c055aab487583a68313ad9a4a3bd1228945ce23e979](https://github.com/msys2/msys2-runtime/commit/3839f28dbf2d09b98e6c6f37e7e0e46eb3d97dda#diff-4ede10814d0ef87034153c055aab487583a68313ad9a4a3bd1228945ce23e979) needs to be ported

Right, Cygwin moved the MINGW helpers into the `winsup/utils/mingw/` directory.

>     * maybe patch cleanup?

Good point. This is a splendid opportunity to do so.

How about squashing ebd6f4324c into 8080a0229b? And df8d982f64 into 76ad9fc839? And 9d25861ca1 into 318eb28f16? And ef04564542 into c63afc809a? And d75f587777 and 43d8fe9aae into 01c15088fb? And 16c31830ff into 86fc68dd9f?

**Comment by dscho** [comment]
>  [dscho](/dscho) [force-pushed](/msys2/msys2-runtime/compare/7a27564505cd6563040b433535a3e808415b1152..b58ed407dbbc4cfe3acbba6549e0eb6a64d0175e) the msys2-3_3_1-release-wip branch from [`7a27564`](/msys2/msys2-runtime/commit/7a27564505cd6563040b433535a3e808415b1152) to [`b58ed40`](/msys2/msys2-runtime/commit/b58ed407dbbc4cfe3acbba6549e0eb6a64d0175e) [21 seconds ago](#event-5583054982)

Let's see how that goes ;-)

**Comment by dscho** [comment]
> > * install broken (something re libmsys-2.0.a)
> 
> I did not see that problem in the workflow runs... Could you share any details?

Ah, I think it's [this](https://github.com/msys2/msys2-runtime/runs/4139701341?check_suite_focus=true#step:5:404):

```
[...]
make[6]: Entering directory '/d/a/msys2-runtime/msys2-runtime/x86_64-pc-msys/winsup/cygwin'
/usr/bin/install -c msys0.dll /d/a/msys2-runtime/msys2-runtime/_dest/usr/bin/msys-2.0.dll
/usr/bin/install -c -m 644 msys-2.0.dbg /d/a/msys2-runtime/msys2-runtime/_dest/usr/bin/msys-2.0.dbg
(cd /d/a/msys2-runtime/msys2-runtime/_dest/usr/x86_64-pc-msys/lib && ln -sf libmsys-2.0.a libg.a)
ln: failed to create symbolic link 'libg.a': No such file or directory
make[6]: *** [Makefile:3011: install-libs] Error 1
[...]
```

BTW before I forget, I think we will also want to have a backport of cygwin/cygwin@1f7aa67b1c9a2db50b04a0f7e539c780b93ccca1. This came up in https://github.com/microsoft/Git-Credential-Manager-Core/issues/509, oddly enough, and would probably affect at least _some_ MSYS2 users.

**Comment by lazka** [comment]
uh, oh, I kinda stopped mid way because I was sleepy and didn't expect anyone to pick it up, I hope it wasn't too confusing.

**Comment by lazka** [comment]
> BTW before I forget, I think we will also want to have a backport of [cygwin/cygwin@1f7aa67](https://github.com/cygwin/cygwin/commit/1f7aa67b1c9a2db50b04a0f7e539c780b93ccca1). This came up in [microsoft/Git-Credential-Manager-Core#509](https://github.com/microsoft/Git-Credential-Manager-Core/issues/509), oddly enough, and would probably affect at least _some_ MSYS2 users.

This should be in the 3.3.2 release already -> https://cygwin.com/git/?p=newlib-cygwin.git;a=shortlog;h=refs/heads/cygwin-3_3-branch

**Comment by dscho** [comment]
> This should be in the 3.3.2 release already

Wait, v3.3.2 has been released already?

**Comment by dscho** [comment]
> I hope it wasn't too confusing.

No, it was quite pleasant to read the range-diff.

> > This should be in the 3.3.2 release already
> 
> Wait, v3.3.2 has been released already?

Oh wow, 10 minutes ago! https://cygwin.com/git/?p=newlib-cygwin.git;a=tag;h=9aa0c0ca7b29438674488dc330512948a6ae7af9

**Comment by dscho** [comment]
> > > This should be in the 3.3.2 release already
> > 
> > 
> > Wait, v3.3.2 has been released already?
> 
> Oh wow, 10 minutes ago! https://cygwin.com/git/?p=newlib-cygwin.git;a=tag;h=9aa0c0ca7b29438674488dc330512948a6ae7af9

Okay, I'll do the rebase.

**Comment by dscho** [comment]
@lazka shall we skip v3.3.1 and continue at https://github.com/msys2/msys2-runtime/pull/63?

**Comment by lazka** [comment]
sure

**Comment by lazka** [comment]
> How about squashing [ebd6f43](https://github.com/msys2/msys2-runtime/commit/ebd6f4324c557bff8d100592253a82dfbee5a347) into [8080a02](https://github.com/msys2/msys2-runtime/commit/8080a0229b97ab8e0e769b5f252bf11d7f5bc4ff)? And [df8d982](https://github.com/msys2/msys2-runtime/commit/df8d982f64253e7679309da9d1d3d2b6a050a1c6) into [76ad9fc](https://github.com/msys2/msys2-runtime/commit/76ad9fc839bd7134dd804d122e417e316e0e0de4)? And [9d25861](https://github.com/msys2/msys2-runtime/commit/9d25861ca1e6ad1211f3b437db31d87bc3164904) into [318eb28](https://github.com/msys2/msys2-runtime/commit/318eb28f1656e12e6b38f506b19ce99f17ada9e4)? And [ef04564](https://github.com/msys2/msys2-runtime/commit/ef045645421772608aad80dae8a79864f9bc6f76) into [c63afc8](https://github.com/msys2/msys2-runtime/commit/c63afc809a81a2ed447164d9fadfe3fcc308e5f1)? And [d75f587](https://github.com/msys2/msys2-runtime/commit/d75f587777179b5ad8558f810781e44407008461) and [43d8fe9](https://github.com/msys2/msys2-runtime/commit/43d8fe9aae23ebf92b85b4f09fad97db1a9628ee) into [01c1508](https://github.com/msys2/msys2-runtime/commit/01c15088fbea2e133f0fc09f367ce7c3095d6338)? And [16c3183](https://github.com/msys2/msys2-runtime/commit/16c31830ff829fd8f66be5d54fc78549331b4e3c) into [86fc68d](https://github.com/msys2/msys2-runtime/commit/86fc68dd9fb2af5a1cc0dec033b07a9bc0406412)?

these all look good to me, thanks

**Pull request closed without merging**
