### PR TITLE
backport arm64 fixes for msys2-3_3_6-release

### PR DESCRIPTION
**Pull request by jeremyd2019**
Since I already did this for testing on Windows 10 ARM64, I thought I'd open a PR for these too.  This is effectively #233 and #234

### CODE REVIEW

**Comment by jeremyd2019** [comment]
I don't use msys2-runtime-3.4, and don't see any use case for it on arm64, so I haven't tried to backport anything to it.

**Comment by lazka** [comment]
-> https://github.com/msys2/MSYS2-packages/pull/5006

**Comment by dscho** [comment]
Does this also need #236?

**Comment by jeremyd2019** [comment]
yes.  I was waiting for confirmation that it fixed the issue.

**Pull request merged**
