### PR TITLE
Cygwin: find_fast_cwd: don't run assembler checking code on ARM64

### LINKED ISSUE #232: MSYS2 / Git broken in Windows 11 Canary build 27744
Currently experiencing this on the Arm64 version of Windows, but it may also apply to x64 versions of Windows.

Both the standalone MSYS2 and the one bundled with Git for Windows fails to load in Windows 11 Canary build 27744. Posting this issue to bring awareness to anyone how may happen to be on the Windows Insider Canary builds and have noticed anything related to using MSYS2 failing to load. 

https://x.com/sinclairinat0r/status/1855733791165169916

### PR DESCRIPTION
**Pull request by dscho**
The code that looks for the `FAST_CWD` pointer seems to crash a lot in recent Canary builds of Windows. This has been fixed in a commit on Cygwin's (yet unreleased) 3.6.0 branch, in 4e77fa9b8b (Cygwin: find_fast_cwd: don't run assembler checking code on ARM64, 2024-02-13), and I already backported this into Git for Windows' fork of the MSYS2 runtime.

Let's backport it to MSYS2 proper, too.

This fixes https://github.com/msys2/msys2-runtime/issues/232

### CODE REVIEW

**Comment by dscho** [comment]
@snickler would you mind testing the [build artifact](https://github.com/msys2/msys2-runtime/actions/runs/11775064830/artifacts/2170251393)?

**Comment by snickler** [comment]
> @snickler would you mind testing the [build artifact](https://github.com/msys2/msys2-runtime/actions/runs/11775064830/artifacts/2170251393)?

Will do!

**Comment by snickler** [comment]
@dscho - WORKS. I replaced the contents of my `usr` directory within the Git install and I'm able to work again!

**Comment by snickler** [comment]
image

Perfection.

**Comment by lazka** [comment]
-> https://github.com/msys2/MSYS2-packages/pull/5000

**Pull request merged**
