### PR TITLE
Sync cygwin

### PR DESCRIPTION
**Pull request by orgads**

### CODE REVIEW

**Comment by dscho** [comment]
@orgads this can be closed, correct?

**Comment by orgads** [comment]
Yeah sure, thanks for the heads up.

**Comment by goyalyashpal** [comment]
hey, what was the commit which was result of this work? I mean, what is the final commit from here which also belongs to the repo??

the 9310e06 above is shown as "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."

**Comment by orgads** [comment]
The branch was rebased IIRC.

**Comment by goyalyashpal** [comment]
so, any clue on how the immediate before and after commit can be found? 

(i don't know git rebase very well, so, sorry if it doesn't make any sense)

**Comment by goyalyashpal** [comment]
- manually ran the [github actions] via `on: [workflow_dispatch]` in the workflow yaml file, 
- but it failed... oh lol... 
- [branch will be deleted soon] https://github.com/yashpalgoyal1304/msys2-runtime/actions/runs/4054814854/jobs/6977122930

[github actions]: https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow

I think it will require more changes to the [workflows/build.yaml] file so that it stays older and what not...

[workflows/build.yaml]: https://github.com/msys2/msys2-runtime/blob/msys2-3.4.5/.github/workflows/build.yaml

but honestly, I guess, i just have to take it on faith that yeah, that issue with "helix outputting garbage when run from bash" is fixed for good, whether be via this commit, or something else... and move on... 6 months been way too long on that issue already.

**Pull request closed without merging**
