### PR TITLE
[backport] Cygwin: console: Fix race issue regarding cons_master_thread().

### PR DESCRIPTION
**Pull request by lazka**
- With this patch, the race issue regarding starting/stopping
  cons_master_thread() introduced by commit ff4440fc is fixed.

  Addresses:
    https://cygwin.com/pipermail/cygwin/2021-April/248292.html

----

See https://github.com/msys2/MSYS2-packages/issues/2471#issuecomment-830572976

### CODE REVIEW

**Comment by cbrt64** [comment]
Regarding the other upstream commits I mentioned, bb93c6d7c2c20d9edfb37d72ca3121cef05efde9 and 01387f1ff41eada228bafacbfb95f49fb8a9aca2 address a different aspect of the same upstream report. I don't know whether they're relevant here.

**Comment by cbrt64** [comment]
Maybe e50db40edfdf5fc38cc30a02a50fd417f58f0094 means that pseudo-console related commits are irrelevant in the short term? Learning as I go, I'll just shut up now.

**Comment by lazka** [comment]
> Maybe [e50db40](https://github.com/msys2/msys2-runtime/commit/e50db40edfdf5fc38cc30a02a50fd417f58f0094) means that pseudo-console related commits are irrelevant in the short term? Learning as I go, I'll just shut up now.

Hard to say, sometimes the changes affect both cases, and the commit message never say what they change.

We will enable pcon by default once the upstream bugfixes slow down.

**Comment by dscho** [comment]
@lazka did you want to keep the PR branch?

**Comment by lazka** [comment]
No, deleted now.

**Comment by jeremyd2019** [comment]
I was hoping that this would solve my pacman hang/deadlock issue on arm64, but no such luck

**Pull request merged**
