### PR TITLE
Update to cygwin 3.3.4

### PR DESCRIPTION
**Pull request by lazka**
Changelog: https://cygwin.com/git/?p=newlib-cygwin.git;a=blob;f=winsup/cygwin/release/3.3.4

Upstream changes: https://github.com/msys2/msys2-runtime/compare/cygwin-3_3_3-release...cygwin-3_3_4-release

Range-Diff:
```
$ git range-diff cygwin-3_3_3-release..msys2-3_3_3-release  cygwin-3_3_4-release..msys2-3_3_4-release-wip
 1:  5c15d5166 =  1:  f9643916d Add MSYS2 triplet
 2:  ca392c50d =  2:  ca24be642 Fix msys library name in import libraries
 3:  3eed7fcf2 !  3:  7c11d96c3 Rename dll from cygwin to msys
    @@ winsup/cygwin/Makefile.am: LIBSERVER = $(cygserver_blddir)/libcygserver.a
      
     -# cygwin dll
     +# msys-2.0 dll
    - $(TEST_DLL_NAME): $(LDSCRIPT) dllfixdbg libdll.a $(VERSION_OFILES) $(LIBSERVER)
    + $(TEST_DLL_NAME): $(LDSCRIPT) dllfixdbg libdll.a $(VERSION_OFILES) $(LIBSERVER)\
    + 		  $(newlib_build)/libm/libm.a $(newlib_build)/libc/libc.a
      	$(CXX) $(CXXFLAGS) \
      	-mno-use-libstdc-wrappers \
      	-Wl,--gc-sections -nostdlib -Wl,-T$(LDSCRIPT) -static \
    @@ winsup/cygwin/fhandler_tty.cc: fhandler_pty_slave::open (int flags, mode_t)
      		       &cygheap->installation_key, get_minor ());
            termios_printf ("dup handles via master control pipe %s", buf);
            if (!CallNamedPipe (buf, &req, sizeof req, &repl, sizeof repl,
    +@@ winsup/cygwin/fhandler_tty.cc: fhandler_pty_slave::reset_switch_to_pcon (void)
    + 		    {
    + 		      char pipe[MAX_PATH];
    + 		      __small_sprintf (pipe,
    ++#ifdef __MSYS__
    ++			       "\\\\.\\pipe\\msys-%S-pty%d-master-ctl",
    ++#else
    + 			       "\\\\.\\pipe\\cygwin-%S-pty%d-master-ctl",
    ++#endif
    + 			       &cygheap->installation_key, get_minor ());
    + 		      pipe_request req = { GetCurrentProcessId () };
    + 		      pipe_reply repl;
     @@ winsup/cygwin/fhandler_tty.cc: fhandler_pty_master::close ()
      	  pipe_reply repl;
      	  DWORD len;
    @@ winsup/cygwin/fhandler_tty.cc: fhandler_pty_master::close ()
      	  __small_sprintf (buf, "\\\\.\\pipe\\cygwin-%S-pty%d-master-ctl",
     +#endif
      			   &cygheap->installation_key, get_minor ());
    - 	  acquire_output_mutex (INFINITE);
    + 	  acquire_output_mutex (mutex_timeout);
      	  if (master_ctl)
     @@ winsup/cygwin/fhandler_tty.cc: fhandler_pty_master::setup ()
      
    @@ winsup/cygwin/fhandler_tty.cc: fhandler_pty_master::setup ()
      		   &cygheap->installation_key, unit);
        master_ctl = CreateNamedPipe (buf, PIPE_ACCESS_DUPLEX
      				     | FILE_FLAG_FIRST_PIPE_INSTANCE,
    +@@ winsup/cygwin/fhandler_tty.cc: fhandler_pty_slave::transfer_input (tty::xfer_dir dir, HANDLE from, tty *ttyp,
    +     {
    +       char pipe[MAX_PATH];
    +       __small_sprintf (pipe,
    ++#ifdef __MSYS__
    ++		       "\\\\.\\pipe\\msys-%S-pty%d-master-ctl",
    ++#else
    + 		       "\\\\.\\pipe\\cygwin-%S-pty%d-master-ctl",
    ++#endif
    + 		       &cygheap->installation_key, ttyp->get_minor ());
    +       pipe_request req = { GetCurrentProcessId () };
    +       pipe_reply repl;
     
      ## winsup/cygwin/fork.cc ##
     @@ winsup/cygwin/fork.cc: frok::child (volatile char * volatile here)
 4:  35991fee2 =  4:  7aa11f8cc Add functionality for converting UNIX paths in arguments and environment variables to Windows form for native Win32 applications.
 5:  e03a663f9 =  5:  3d15b852e Add functionality for changing OS name via MSYSTEM environment variables.
 6:  4cdd9aa91 =  6:  d47a06e48 - Move root to /usr. - Change sorting mount points. - By default mount without ACLs. - Can read /etc/fstab with short mount point format.
 7:  62230a69b =  7:  a670005c0 Instead of creating Cygwin symlinks, use deep copy by default
 8:  5c2e91ef1 =  8:  fc13a82e7 Automatically rewrite TERM=msys to TERM=cygwin With MSys1, it was necessary to set the TERM variable to "msys". To allow for a smooth transition from MSys1 to MSys2, let's simply handle TERM=msys as if the user had not specified TERM at all and wanted us to use our preferred TERM value.
 9:  5dfe4233a =  9:  54d87bc5f Do not convert environment for strace
10:  33dd3a5a5 = 10:  3707c635b Special case for converting root directory to have training slash
11:  1fdc45c4d = 11:  110b516ad dcrt0.cc: Untangle allow_glob from winshell
12:  9b81d2008 = 12:  1ed5efd95 dcrt0.cc (globify): Don't quote literal strings differently when dos_spec
13:  b1f05f3ba = 13:  2336464e1 strace.cc: Don't set MSYS=noglob
14:  fb1561445 = 14:  eede69db2 Add debugging for build_argv
15:  a34872bc4 = 15:  72a34b304 Add debugging for strace make_command_line
16:  abe86aa09 = 16:  125291daa environ.cc: New facility/environment variable MSYS2_ENV_CONV_EXCL
17:  e816b77b3 = 17:  a4090bf77 Fix native symbolic link spawn passing wrong arg0
18:  da43030d3 = 18:  57c449341 QueryUnbiasedInterruptTime must be load from kernel32.dll
19:  2d8cdeeaa = 19:  e893c7b58 strace --quiet: be *really* quiet
20:  893877240 = 20:  83ef4040f Default to `disable_pcon`
21:  9e8008135 = 21:  c2726e74a Introduce the `enable_pcon` value for `MSYS`
22:  83ec4066e = 22:  055a8a31e popen: call /usr/bin/sh instead of /bin/sh
23:  a99dc3eaa ! 23:  b4f09af08 CI: add a GHA for doing a basic build test
    @@ .github/workflows/build.yaml (new)
     +        with:
     +          msystem: MSYS
     +          update: true
    -+          install: msys2-devel base-devel cocom diffutils gcc gettext-devel libiconv-devel make mingw-w64-cross-crt mingw-w64-cross-gcc mingw-w64-cross-zlib perl zlib-devel
    ++          install: msys2-devel base-devel autotools cocom diffutils gcc gettext-devel libiconv-devel make mingw-w64-cross-crt mingw-w64-cross-gcc mingw-w64-cross-zlib perl zlib-devel xmlto docbook-xsl
     +
     +      - name: Build
     +        shell: msys2 {0}
24:  f9e55f376 = 24:  c4438da53 Set up a GitHub Action to keep in sync with Cygwin
25:  4ca6df7d5 = 25:  7bafcb508 Expose full command-lines to other Win32 processes by default
26:  cec4a1da1 = 26:  cd0185989 Disable the 'cygwin' GitHub workflow
27:  8fca9906b = 27:  32be09faa Do not show Error dialogs by default
28:  ceceb6002 = 28:  1d6275df3 Add a helper to obtain a function's address in kernel32.dll
29:  dfae2ddcf = 29:  eab174266 Emulate GenerateConsoleCtrlEvent() upon Ctrl+C
30:  0905fe0cf = 30:  fc51dc797 kill: kill Win32 processes more gently
31:  9128b4ba7 = 31:  ab1bb9b98 Cygwin: make option for native inner link handling.
32:  a04387a79 = 32:  0a97711e0 docs: skip building texinfo and PDF files
33:  27276c6ba = 33:  498472391 install-libs: depend on the "toollibs"
34:  3c5922703 <  -:  --------- fixup! Rename dll from cygwin to msys
35:  eb5547505 <  -:  --------- Cygwin: pty: fix bug in reduced input transfer
36:  0efcde460 <  -:  --------- Cygwin: path: Convert UNC path prefix back to drive letter.
37:  2480c0e32 <  -:  --------- Cygwin: path: Fix path conversion of virtual drive.
38:  f2fd51bcb <  -:  --------- fixup! CI: add a GHA for doing a basic build test
39:  e4fbec279 <  -:  --------- Cygwin: fhandler_pipe::get_query_hdl_per_process: avoid a crash
40:  390150d2b = 34:  648860426 POSIX-ify the SHELL variable
41:  c04503a3e = 35:  c0250d576 Handle ORIGINAL_PATH just like PATH
42:  08e8d57dd <  -:  --------- fixup! CI: add a GHA for doing a basic build test
43:  576eff4d5 <  -:  --------- posix_spawn: fix get/set uid/gid calls for 32 bit Cygwin
44:  7a2c16a75 <  -:  --------- path_conv: a directory with `.lnk` suffix is not a `.lnk` file
```

### CODE REVIEW

**Comment by jeremyd2019** [comment]
I think for the range-diff you want msys2-3_3_4-release-wip

**Comment by lazka** [comment]
> I think for the range-diff you want msys2-3_3_4-release-wip

oops, thanks, I was just wondering that.

edit: done, fixed the instructions in the wiki as well

**Comment by dscho** [comment]
> the instructions in the wiki as well

https://github.com/msys2/msys2-runtime/wiki#rebase-on-top-of-a-new-cygwin-release looks good, and very automatable...

**Comment by dscho** [comment]
> 35:  eb5547505 <  -:  --------- Cygwin: pty: fix bug in reduced input transfer

This is upstream as c54b890bc7, in a quite different shape, but clearly the same underlying idea.

> 36:  0efcde460 <  -:  --------- Cygwin: path: Convert UNC path prefix back to drive letter.

This is upstream as 1b40f151cd.

> 37:  2480c0e32 <  -:  --------- Cygwin: path: Fix path conversion of virtual drive.

This is upstream as 

> 39:  e4fbec279 <  -:  --------- Cygwin: fhandler_pipe::get_query_hdl_per_process: avoid a crash

> 43:  576eff4d5 <  -:  --------- posix_spawn: fix get/set uid/gid calls for 32 bit Cygwin
> 44:  7a2c16a75 <  -:  --------- path_conv: a directory with `.lnk` suffix is not a `.lnk` file

**Comment by dscho** [comment]
> 35:  eb5547505 <  -:  --------- Cygwin: pty: fix bug in reduced input transfer

This is upstream as c54b890bc7, in a quite different shape, but clearly the same underlying idea.

> 36:  0efcde460 <  -:  --------- Cygwin: path: Convert UNC path prefix back to drive letter.

This is upstream as 1b40f151cd.

> 37:  2480c0e32 <  -:  --------- Cygwin: path: Fix path conversion of virtual drive.

This is upstream as c2f39a543e.

> 39:  e4fbec279 <  -:  --------- Cygwin: fhandler_pipe::get_query_hdl_per_process: avoid a crash

This is upstream as 987689a3ba.

> 43:  576eff4d5 <  -:  --------- posix_spawn: fix get/set uid/gid calls for 32 bit Cygwin

This is upstream as 50405603ea

> 44:  7a2c16a75 <  -:  --------- path_conv: a directory with `.lnk` suffix is not a `.lnk` file

This is upstream as 7a8622667f.

**Review by dscho — APPROVED** [review]

**Comment by lazka** [comment]
Thanks

(I should have added the info for the removed commits. I'll do that next time)

**Pull request merged**
