### PR TITLE
Rebase to v3.5.5

### PR DESCRIPTION
**Pull request by dscho**
<details><summary>range-diff relative to v3.5.4</summary>

* 1:  51380ec75b =  1:  bdad035f0b Add MSYS2 triplet
* 2:  a116f41845 =  2:  900232bfff Fix msys library name in import libraries
* 3:  f858c02bdb !  3:  585fadf7ea Rename dll from cygwin to msys

   ``````diff
   @@ winsup/cygwin/syscalls.cc: try_to_bin (path_conv &pc, HANDLE &fh, ACCESS_MASK ac
         {
    -      /* Create unique filename.  Start with a dot, followed by "cyg"
    +      /* Create unique filename.  Start with a dot, followed by "msys"
   - 	 transposed into the Unicode low surrogate area (U+dc00) on file
   - 	 systems supporting Unicode (except Samba), followed by the inode
   - 	 number in hex, followed by a path hash in hex.  The combination
   + 	 transposed to the Unicode private use area in the U+f700 area
   + 	 on file systems supporting Unicode (except Samba), followed by
   + 	 the inode number in hex, followed by a path hash in hex.  The
    @@ winsup/cygwin/syscalls.cc: try_to_bin (path_conv &pc, HANDLE &fh, ACCESS_MASK access, ULONG flags)
           RtlAppendUnicodeToString (&recycler,
     				(pc.fs_flags () & FILE_UNICODE_ON_DISK
     				 && !pc.fs_is_samba ())
   --				? L".\xdc63\xdc79\xdc67" : L".cyg");
   -+				? L".\xdc6d\xdc73\xdc79\xdc73" : L".msys");
   +-				? L".\xf763\xf779\xf767" : L".cyg");
   ++				? L".\xf76d\xf773\xf779\xf773" : L".msys");
           pfii = (PFILE_INTERNAL_INFORMATION) infobuf;
           status = NtQueryInformationFile (fh, &io, pfii, sizeof *pfii,
     				       FileInternalInformation);
   ``````

* 4:  b084abe0ec =  4:  d076660c2d Add functionality for converting UNIX paths in arguments and environment variables to Windows form for native Win32 applications.
* 5:  f16038529a =  5:  35a477b5cd Add functionality for changing OS name via MSYSTEM environment variables.
* 6:  6393488c9d =  6:  41ed62e6f5 - Move root to /usr. - Change sorting mount points. - By default mount without ACLs. - Can read /etc/fstab with short mount point format.
* 7:  06ea20e4ec =  7:  8096583fac Instead of creating Cygwin symlinks, use deep copy by default
* 8:  222fd37c0b =  8:  0ba54e8cc1 Automatically rewrite TERM=msys to TERM=cygwin
* 9:  41e8ada0d1 =  9:  e28b7422e2 Do not convert environment for strace
* 10:  766e55c1be = 10:  4a24304b8b strace.cc: Don't set MSYS=noglob
* 11:  4f01c3f5c7 = 11:  b3a4a5bd44 Add debugging for strace make_command_line
* 12:  d43f1eebf2 = 12:  f8c098028c strace --quiet: be *really* quiet
* 13:  0053f7b38e = 13:  c4d9d83ede path_conv: special-case root directory to have trailing slash
* 14:  1e8a891f5e = 14:  1c5a6e869c When converting to a Unix path, avoid double trailing slashes
* 15:  673065dd1e = 15:  8b5e9b55a1 msys2_path_conv: pass PC_NOFULL to path_conv
* 16:  e1db14849f = 16:  b09fb7fd5a path-conversion: Introduce ability to switch off conversion.
* 17:  f6e516da39 = 17:  b2391806db dcrt0.cc: Untangle allow_glob from winshell
* 18:  1059fbbdea = 18:  1e94f3ee1d dcrt0.cc (globify): Don't quote literal strings differently when dos_spec
* 19:  f8da08fd7e = 19:  e6c5e3ec30 Add debugging for build_argv
* 20:  03d6fe120a = 20:  d44fc10030 environ.cc: New facility/environment variable MSYS2_ENV_CONV_EXCL
* 21:  90d66ee649 = 21:  98c164175f Fix native symbolic link spawn passing wrong arg0
* 22:  7b84fed8f0 = 22:  d12ab6d59c Introduce the `enable_pcon` value for `MSYS`
* 23:  6f87e23bae = 23:  865ad5d64e popen: call /usr/bin/sh instead of /bin/sh
* 24:  df7a56eeaa = 24:  5f36fdbfcd Disable the 'cygwin' GitHub workflow
* 25:  cf56ccdb64 ! 25:  862887f29f CI: add a GHA for doing a basic build test

   ``````diff
   @@ .github/workflows/build.yaml (new)
    +
    +    steps:
    +      - name: Checkout code
   -+        uses: actions/checkout@v3
   ++        uses: actions/checkout@v4
    +
    +      - name: setup-msys2
    +        uses: msys2/setup-msys2@v2
   @@ .github/workflows/build.yaml (new)
    +          make DESTDIR="$(pwd)"/_dest install
    +
    +      - name: Upload
   -+        uses: actions/upload-artifact@v3
   ++        uses: actions/upload-artifact@v4
    +        with:
    +          name: install
    +          path: _dest/
   ``````

* 26:  083c245339 = 26:  764bd7fb8f CI: fix the build with gcc 13
* 27:  91f46dfb4b = 27:  bea6a078ca Set up a GitHub Action to keep in sync with Cygwin
* 28:  4dd6aad863 = 28:  080e2b0f6a Expose full command-lines to other Win32 processes by default
* 29:  6ef58ed329 = 29:  9f45f58388 Add a helper to obtain a function's address in kernel32.dll
* 30:  38a8880717 = 30:  f6f7e2c928 Emulate GenerateConsoleCtrlEvent() upon Ctrl+C
* 31:  b9d1fadafe = 31:  86cd50d151 kill: kill Win32 processes more gently
* 32:  715f6ce891 = 32:  4b228ef2e4 Cygwin: make option for native inner link handling.
* 33:  abeeb31b2b = 33:  6e0c3b56c7 docs: skip building texinfo and PDF files
* 34:  fbe8ae30a3 = 34:  ecf50e64ce install-libs: depend on the "toollibs"
* 35:  38abc7cfff = 35:  8cb4ff2c0e POSIX-ify the SHELL variable
* 36:  9c758e8f9c = 36:  1f6020c6bf Handle ORIGINAL_PATH just like PATH
* 37:  312f7660cc = 37:  79e3880244 uname: allow setting the system name to CYGWIN
* 38:  e19af2018e = 38:  ef59c45434 Pass environment variables with empty values
* 39:  4deb751587 = 39:  c347d6c26b Optionally disallow empty environment values again
* 40:  a1f282d18d = 40:  210e5f3c4d build_env(): respect the `MSYS` environment variable
* 41:  d1b382b8d6 = 41:  bef1e6ba82 Revert "Cygwin: Enable dynamicbase on the Cygwin DLL by default"
* 42:  997f6f3ea0 = 42:  8103a099cf CI: set -Wno-error=maybe-uninitialized
* 43:  e347515e99 = 43:  6e10b1bdd9 Avoid sharing cygheaps across Cygwin versions
* 44:  dd9d970a97 = 44:  f61f7fb71a uname: report msys2-runtime commit hash, too
* 45:  2bfb7739da <  -:  ---------- Cygwin: pipe: Fix a regression that raw_write() slows down
* 46:  16dfe943bc = 45:  debafbf93f Cygwin: find_fast_cwd: don't run assembler checking code on ARM64
* 47:  e09c64ef65 ! 46:  2c55ca50ee cygthread: suspend thread before terminating.

   ``````diff
   @@ winsup/cygwin/cygthread.cc: cygthread::terminate_thread ()
       WaitForSingleObject (h, INFINITE);
       CloseHandle (h);
    
   + ## winsup/cygwin/pinfo.cc ##
   +@@ winsup/cygwin/pinfo.cc: proc_waiter (void *arg)
   + 
   +   for (;;)
   +     {
   +-      DWORD nb;
   ++      DWORD nb, err;
   +       char buf = '\0';
   + 
   +       if (!ReadFile (vchild.rd_proc_pipe, &buf, 1, &nb, NULL)
   +-	  && GetLastError () != ERROR_BROKEN_PIPE)
   ++	  && (err = GetLastError ()) != ERROR_BROKEN_PIPE)
   + 	{
   +-	  system_printf ("error on read of child wait pipe %p, %E", vchild.rd_proc_pipe);
   ++	  /* ERROR_OPERATION_ABORTED is expected due to the possibility that
   ++	     CancelSynchronousIo interruped the ReadFile call, so don't output
   ++	     that error */
   ++	  if (err != ERROR_OPERATION_ABORTED)
   ++	    system_printf ("error on read of child wait pipe %p, %E", vchild.rd_proc_pipe);
   + 	  break;
   + 	}
   + 
   +
     ## winsup/cygwin/sigproc.cc ##
    @@ winsup/cygwin/sigproc.cc: proc_terminate ()
   + 	     to 1 iff it is a Cygwin process.  */
     	  if (!have_execed || !have_execed_cygwin)
     	    chld_procs[i]->ppid = 1;
   - 	  if (chld_procs[i].wait_thread)
   --	    chld_procs[i].wait_thread->terminate_thread ();
   -+	    if (!CancelSynchronousIo (chld_procs[i].wait_thread->thread_handle ()))
   -+	      chld_procs[i].wait_thread->terminate_thread ();
   +-	  if (chld_procs[i].wait_thread)
   ++	  /* Attempt to exit the wait_thread cleanly via CancelSynchronousIo
   ++	     before falling back to the (explicitly dangerous) cross-thread
   ++	     termination */
   ++	  if (chld_procs[i].wait_thread
   ++	      && !CancelSynchronousIo (chld_procs[i].wait_thread->thread_handle ()))
   + 	    chld_procs[i].wait_thread->terminate_thread ();
     	  /* Release memory associated with this process unless it is 'myself'.
     	     'myself' is only in the chld_procs table when we've execed.  We
   - 	     reach here when the next process has finished initializing but we
   +@@ winsup/cygwin/sigproc.cc: remove_proc (int ci)
   + {
   +   if (have_execed)
   +     {
   +-      if (_my_tls._ctinfo != chld_procs[ci].wait_thread)
   ++      /* Attempt to exit the wait_thread cleanly via CancelSynchronousIo
   ++	 before falling back to the (explicitly dangerous) cross-thread
   ++	 termination */
   ++      if (_my_tls._ctinfo != chld_procs[ci].wait_thread
   ++	  && !CancelSynchronousIo (chld_procs[ci].wait_thread->thread_handle ()))
   + 	chld_procs[ci].wait_thread->terminate_thread ();
   +     }
   +   else if (chld_procs[ci] && chld_procs[ci]->exists ())
   ``````

* 48:  eafd9a22bc <  -:  ---------- fixup! cygthread: suspend thread before terminating.
* 49:  7829673c0c <  -:  ---------- fixup! cygthread: suspend thread before terminating.
* 50:  3cd86092c5 <  -:  ---------- fixup! CI: add a GHA for doing a basic build test
* 51:  2eb6be14ee = 47:  e5dc132b3f Cygwin: revert use of CancelSyncronousIo on wait_thread.
* 52:  fe383b0dad = 48:  5453f9fab6 Cygwin: cache IsWow64Process2 host arch in wincap.
* 53:  8d847f4e94 = 49:  985e2654b8 Cygwin: uname: add host machine tag to sysname.

</details>

### CODE REVIEW

**Comment by jeremyd2019** [comment]
> * 3:  [f858c02](https://github.com/msys2/msys2-runtime/commit/f858c02bdb8d3444691dd99165718a1dd67ea753) !  3:  [585fadf](https://github.com/msys2/msys2-runtime/commit/585fadf7eab7cc83f6445adcd30b5c2b2e9357f8) Rename dll from cygwin to msys
>   ```diff
>   @@ winsup/cygwin/syscalls.cc: try_to_bin (path_conv &pc, HANDLE &fh, ACCESS_MASK ac
>         {
>    -      /* Create unique filename.  Start with a dot, followed by "cyg"
>    +      /* Create unique filename.  Start with a dot, followed by "msys"
>   - 	 transposed into the Unicode low surrogate area (U+dc00) on file
>   - 	 systems supporting Unicode (except Samba), followed by the inode
>   - 	 number in hex, followed by a path hash in hex.  The combination
>   + 	 transposed to the Unicode private use area in the U+f700 area
>   + 	 on file systems supporting Unicode (except Samba), followed by
>   + 	 the inode number in hex, followed by a path hash in hex.  The
>    @@ winsup/cygwin/syscalls.cc: try_to_bin (path_conv &pc, HANDLE &fh, ACCESS_MASK access, ULONG flags)
>           RtlAppendUnicodeToString (&recycler,
>     				(pc.fs_flags () & FILE_UNICODE_ON_DISK
>     				 && !pc.fs_is_samba ())
>   --				? L".\xdc63\xdc79\xdc67" : L".cyg");
>   -+				? L".\xdc6d\xdc73\xdc79\xdc73" : L".msys");
>   +-				? L".\xf763\xf779\xf767" : L".cyg");
>   ++				? L".\xf76d\xf773\xf779\xf773" : L".msys");
>           pfii = (PFILE_INTERNAL_INFORMATION) infobuf;
>           status = NtQueryInformationFile (fh, &io, pfii, sizeof *pfii,
>     				       FileInternalInformation);
>   ```

Huh, there was more discussion about the unpaired surrogates causing issues, but I didn't notice a cygwin-patches patch changing them, let alone backporting the change to 3.5.

**Comment by lazka** [comment]
> Huh, there was more discussion about the unpaired surrogates causing issues, but I didn't notice a cygwin-patches patch changing them, let alone backporting the change to 3.5.

https://github.com/cygwin/cygwin/commit/bb854e0 for reference

**Comment by lazka** [comment]
lgtm

**Comment by dscho** [comment]
➡️https://github.com/msys2/MSYS2-packages/pull/5095

**Comment by jeremyd2019** [comment]
There are some reports of hangs on the Cygwin mailing list, possibly due to changes in signal handling that are messing up `SIGCHLD` somehow (it looked like Takashi had a patch in https://cygwin.com/pipermail/cygwin-patches/2024q4/013145.html)

**Comment by lazka** [comment]
I'll keep it in staging for now.

**Comment by jeremyd2019** [comment]
A build was hung on arm64, I had to kill a sh.exe process (I tried `kill -CHLD` on the sh and parent make process, but neither worked)

**Comment by dscho** [comment]
> A build was hung on arm64, I had to kill a sh.exe process (I tried `kill -CHLD` on the sh and parent make process, but neither worked)

@jeremyd2019 should we fast-track https://github.com/msys2/msys2-runtime/pull/251 and see whether it addresses the hangs? In case Cygwin decides to go with a different version of the patch, we can always revert and apply the new one...

**Comment by jeremyd2019** [comment]
I don't know - it seems like reports are still coming in of issues, but most of them Takashi suggests will be fixed by that patch.  Currently outstanding is https://inbox.sourceware.org/cygwin/20241225230834.b21c465455c4542854464d07@nifty.ne.jp/T/#t

**Comment by jeremyd2019** [comment]
it seems to have hung again building imagemagick on arm64, so might be worth a try (think I'll try to hold back msys2-runtime and make sure it doesn't hang with 3.5.4)

**Comment by jeremyd2019** [comment]
Hung 3 times with 3.5.5, worked first try with 3.5.4

**Pull request merged**
