### PR TITLE
Fix sub_convert debug output

### PR DESCRIPTION
**Pull request by dg0yt**
Noticed in msys2-tests repository.

### CODE REVIEW

**Review by dscho — APPROVED** [review]
Obviously correct!

**Comment by dscho** [comment]
@lazka do you have any idea why the CI failed?

**Comment by dg0yt** [comment]
BTW I found a second statement with missing `\n`. But I may need a few days to add this.

**Comment by lazka** [comment]
I think we updated gcc in the meantime.

**Comment by lazka** [comment]
> I think we updated gcc in the meantime.

ah, yes , I forgot, I dealt with the same issue here: https://github.com/msys2/MSYS2-packages/commit/6cbd16b459da5e646ad2465b0d8ee64d756a9373

I will

* disable werror for now to make CI green again
* upgrade the cross compiler so that the same CFLAGS are understood by both compilers
* replace wno-error with disabling specific warnings, so we avoid hiding real errors
* hope cygwin updates their toolchain some time

**Comment by lazka** [comment]
#177

**Comment by dg0yt** [comment]
Is this really correct? :thinking: 
~~~
$ git grep debug_printf | grep -v '\\n' | wc -l
937
$ git grep debug_printf | grep '\\n' | wc -l
14

**Comment by dscho** [comment]
> Is this really correct? 🤔
> 
> ```
> $ git grep debug_printf | grep -v '\\n' | wc -l
> 937
> $ git grep debug_printf | grep '\\n' | wc -l
> 14
> ```

Oh hahaha! I had not realized that the `debug_printf()` function (which is actually a macro that expands to another macro which eventually expands to `strace.printf()`) is backed by a function that [automatically appends a newline unless there is already one](https://github.com/msys2/msys2-runtime/blob/78f82c3df178984dc8119af3bbc82856060b0b77/winsup/cygwin/strace.cc#L192-L209)... So I guess this PR is not needed?

Note, however, that this is very different from the `small_printf()` function (with whose behavior I was confused to believe that this here PR was needed), which does distinctly [not append a newline at all](https://github.com/msys2/msys2-runtime/blob/78f82c3df178984dc8119af3bbc82856060b0b77/winsup/cygwin/smallprint.cc#L127-L354).

**Comment by dg0yt** [comment]
Maybe it is easier to always add/print `\n` in msys2-tests.

**Pull request closed without merging**
