### PR TITLE
Rebase to Cygwin v3.5.1

### PR DESCRIPTION
**Pull request by dscho**
<details><summary>Range-diff relative to msys2-3.5.0</summary>

* 1:  032b7eaf84 =  1:  466f9bc0c0 Add MSYS2 triplet
* 2:  b5b80682ea =  2:  29cbc0b992 Fix msys library name in import libraries
* 3:  a282a19dd1 =  3:  d958d215d3 Rename dll from cygwin to msys
* 4:  fc9b833752 =  4:  ea53dd6550 Add functionality for converting UNIX paths in arguments and environment variables to Windows form for native Win32 applications.
* 5:  a5a0cba0c5 =  5:  658607eab1 Add functionality for changing OS name via MSYSTEM environment variables.
* 6:  bc1a633037 =  6:  a4833b5e63 - Move root to /usr. - Change sorting mount points. - By default mount without ACLs. - Can read /etc/fstab with short mount point format.
* 7:  791aadb566 !  7:  6881300ba3 Instead of creating Cygwin symlinks, use deep copy by default

   ``````diff
   @@ winsup/cygwin/globals.cc: bool ignore_case_with_glob;
    -winsym_t allow_winsymlinks = WSYM_default;
    +winsym_t allow_winsymlinks = WSYM_deepcopy;
     bool disable_pcon;
   + bool winjitdebug = false;
     
   - /* Taken from BSD libc:
    
     ## winsup/cygwin/path.cc ##
    @@ winsup/cygwin/path.cc: conv_path_list (const char *src, char *dst, size_t size,
   ``````

* 8:  6424ec5520 =  8:  36560075d4 Automatically rewrite TERM=msys to TERM=cygwin
* 9:  dd68e838b3 =  9:  f6436d4edd Do not convert environment for strace
* 10:  df746f8ca3 = 10:  5efcac483d path_conv: special-case root directory to have trailing slash
* 11:  27a7ee531f = 11:  a758d14496 dcrt0.cc: Untangle allow_glob from winshell
* 12:  f7208503f2 = 12:  921063a246 dcrt0.cc (globify): Don't quote literal strings differently when dos_spec
* 13:  cc7f4c397c = 13:  68f682c224 strace.cc: Don't set MSYS=noglob
* 14:  6d24e9e215 = 14:  be8f9d03a8 Add debugging for build_argv
* 15:  d8cb51c810 = 15:  a655c3368b Add debugging for strace make_command_line
* 16:  79cd04c3ce = 16:  a2cdd69f31 environ.cc: New facility/environment variable MSYS2_ENV_CONV_EXCL
* 17:  d1d1fb1f38 = 17:  759dd9a3a7 Fix native symbolic link spawn passing wrong arg0
* 18:  1add8e74f7 = 18:  3e03940f0d strace --quiet: be *really* quiet
* 19:  b614817573 ! 19:  2e9f8f57aa Introduce the `enable_pcon` value for `MSYS`

   ``````diff
   @@ winsup/cygwin/environ.cc: enum settings
       };
     
    @@ winsup/cygwin/environ.cc: static struct parse_thing
   -   {"wincmdln", {&wincmdln}, setbool, NULL, {{false}, {true}}},
   -   {"winsymlinks", {func: set_winsymlinks}, isfunc, NULL, {{0}, {0}}},
   +   } known[] NO_COPY =
   + {
       {"disable_pcon", {&disable_pcon}, setbool, NULL, {{false}, {true}}},
    +  {"enable_pcon", {&disable_pcon}, setnegbool, NULL, {{true}, {false}}},
   -   {NULL, {0}, setdword, 0, {{0}, {0}}}
   - };
   - 
   +   {"error_start", {func: error_start_init}, isfunc, NULL, {{0}, {0}}},
   +   {"export", {&export_settings}, setbool, NULL, {{false}, {true}}},
   +   {"glob", {func: glob_init}, isfunc, NULL, {{0}, {s: "normal"}}},
    @@ winsup/cygwin/environ.cc: parse_options (const char *inbuf)
     		  *k->setting.b = !!strtol (eq, NULL, 0);
     		debug_printf ("%s%s", *k->setting.b ? "" : "no", k->name);
   ``````

* 20:  ddbc71a8a3 = 20:  d39ad7c47d popen: call /usr/bin/sh instead of /bin/sh
* 21:  8e53ed2d11 = 21:  dee23f47d2 Disable the 'cygwin' GitHub workflow
* 22:  52ddcbe23f = 22:  29fda5b743 CI: add a GHA for doing a basic build test
* 23:  192f8a8122 = 23:  ebc3757e11 Set up a GitHub Action to keep in sync with Cygwin
* 24:  38573b506e ! 24:  f9f1f42d25 Expose full command-lines to other Win32 processes by default

   ``````diff
   @@ winsup/cygwin/globals.cc: bool allow_glob = true;
    +bool wincmdln = true;
     winsym_t allow_winsymlinks = WSYM_deepcopy;
     bool disable_pcon;
   - 
   + bool winjitdebug = false;
    
     ## winsup/doc/cygwinenv.xml ##
    @@ winsup/doc/cygwinenv.xml: time and when handles are inherited.  Defaults to set.</para>
   ``````

* 25:  5d63aaac8b <  -:  ---------- Do not show Error dialogs by default
* 26:  cbde0ba175 = 25:  5b98304fbd Add a helper to obtain a function's address in kernel32.dll
* 27:  3671a984cd = 26:  35a36917e5 Emulate GenerateConsoleCtrlEvent() upon Ctrl+C
* 28:  04ba8677be = 27:  27c90efcbe kill: kill Win32 processes more gently
* 29:  151bb0bd86 ! 28:  804211ffd8 Cygwin: make option for native inner link handling.

   ``````diff
   @@ Commit message
    
     ## winsup/cygwin/environ.cc ##
    @@ winsup/cygwin/environ.cc: static struct parse_thing
   -   {"disable_pcon", {&disable_pcon}, setbool, NULL, {{false}, {true}}},
   -   {"enable_pcon", {&disable_pcon}, setnegbool, NULL, {{true}, {false}}},
   -   {"winjitdebug", {&winjitdebug}, setbool, NULL, {{false}, {true}}},
   +   {"error_start", {func: error_start_init}, isfunc, NULL, {{0}, {0}}},
   +   {"export", {&export_settings}, setbool, NULL, {{false}, {true}}},
   +   {"glob", {func: glob_init}, isfunc, NULL, {{0}, {s: "normal"}}},
    +  {"nativeinnerlinks", {&nativeinnerlinks}, setbool, NULL, {{false}, {true}}},
   -   {NULL, {0}, setdword, 0, {{0}, {0}}}
   - };
   - 
   +   {"pipe_byte", {&pipe_byte}, setbool, NULL, {{false}, {true}}},
   +   {"proc_retry", {func: set_proc_retry}, isfunc, NULL, {{0}, {5}}},
   +   {"reset_com", {&reset_com}, setbool, NULL, {{false}, {true}}},
    
     ## winsup/cygwin/globals.cc ##
    @@ winsup/cygwin/globals.cc: bool wincmdln = true;
   ``````

* 30:  680d9d7c7d = 29:  1300003989 docs: skip building texinfo and PDF files
* 31:  745587f347 = 30:  9884b64658 install-libs: depend on the "toollibs"
* 32:  23dbe3abb3 = 31:  c90f0a9e41 POSIX-ify the SHELL variable
* 33:  678f413e6f = 32:  4f0efbcd57 Handle ORIGINAL_PATH just like PATH
* 34:  a7b2f4cd70 = 33:  87bfb4525d uname: allow setting the system name to CYGWIN
* 35:  d10a450c30 = 34:  b0fa877324 Pass environment variables with empty values
* 36:  9cdf6577db ! 35:  126284461c Optionally disallow empty environment values again

   ``````diff
   @@ winsup/cygwin/environ.cc: static char **lastenviron;
     enum settings
       {
    @@ winsup/cygwin/environ.cc: static struct parse_thing
   -   {"enable_pcon", {&disable_pcon}, setnegbool, NULL, {{true}, {false}}},
   -   {"winjitdebug", {&winjitdebug}, setbool, NULL, {{false}, {true}}},
   -   {"nativeinnerlinks", {&nativeinnerlinks}, setbool, NULL, {{false}, {true}}},
   +   } known[] NO_COPY =
   + {
   +   {"disable_pcon", {&disable_pcon}, setbool, NULL, {{false}, {true}}},
    +  {"emptyenvvalues", {&emptyenvvalues}, setbool, NULL, {{false}, {true}}},
   -   {NULL, {0}, setdword, 0, {{0}, {0}}}
   - };
   - 
   +   {"enable_pcon", {&disable_pcon}, setnegbool, NULL, {{true}, {false}}},
   +   {"error_start", {func: error_start_init}, isfunc, NULL, {{0}, {0}}},
   +   {"export", {&export_settings}, setbool, NULL, {{false}, {true}}},
    @@ winsup/cygwin/environ.cc: build_env (const char * const *envp, PWCHAR &envblock, int &envc,
     	     Note that this doesn't stop invalid strings without '=' in it
     	     etc., but we're opting for speed here for now.  Adding complete
   ``````

* 37:  8f9faea211 = 36:  4a9db817fd build_env(): respect the `MSYS` environment variable
* 38:  3bd47a4e2b = 37:  c7908f7f06 When converting to a Unix path, avoid double trailing slashes
* 39:  e0e8caeae5 = 38:  8b63bbdf1c msys2_path_conv: pass PC_NOFULL to path_conv
* 40:  2a46fefe5a = 39:  5b4115a989 Revert "Cygwin: Enable dynamicbase on the Cygwin DLL by default"
* 41:  06562dd490 <  -:  ---------- dumper: avoid linker problem when `libbfd` depends on `libsframe`
* 42:  cb636605ce = 40:  6ac0ba6d48 CI: fix the build with gcc 13
* 43:  e75096f3e1 = 41:  4762c7192c path-conversion: Introduce ability to switch off conversion.
* 44:  42e244512c = 42:  cbe0932688 proc: fix `error: the address of ΓÇÿiso15924ΓÇÖ will never be NULL`
* 45:  2ba3c86744 <  -:  ---------- Cygwin: console: Fix exit code for non-cygwin process.
* 46:  ef393717bb <  -:  ---------- Work around fragile `#include` in binutils
* 47:  ec35e8a470 <  -:  ---------- Cygwin: console: Avoid slipping past disable_master_thread check.
* 48:  c73fabb33a <  -:  ---------- Cygwin: pty: Fix handle leak in master process.
* 49:  41499b18c4 <  -:  ---------- Cygwin: pty: Fix potential handle leak regarding CallNamedPipe().
* 50:  51aae37287 <  -:  ---------- Cygwin: console: Make VMIN and VTIME work.
* 51:  711907eb6c <  -:  ---------- Cygwin: console: Fix a problem that minor ID is incorrect in ConEmu.

</details>

The "deleted" patches can be explained by quite a couple of backports as well as upstreamed patches or patches that were implemented independently by Cygwin.

<details><summary>"Do not show Error dialogs by default" (upstreamed)</summary>

   ``````

* 1:  5d63aaac8b ! 1:  6d6e1e354d Do not show Error dialogs by default

   ``````diff
   @@ Metadata
    Author: Johannes Schindelin <johannes.schindelin@gmx.de>
    
     ## Commit message ##
   -    Do not show Error dialogs by default
   +    Cygwin: Do not show Error dialogs by default
   +
   +    ...in a non-Cygwin child process.  Backported from MSYS2.
   +    Downstream commit message follows.
    
        In https://github.com/msys2/msys2-runtime/pull/18, we discussed a change
        that would allow default Windows error handling of spawned processes to
   @@ Commit message
        variable `MSYS`) at long last.
    
        Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>
   +    Signed-off-by: Corinna Vinschen <corinna@vinschen.de>
    
     ## winsup/cygwin/environ.cc ##
    @@ winsup/cygwin/environ.cc: static struct parse_thing
   +   {"wincmdln", {&wincmdln}, setbool, NULL, {{false}, {true}}},
       {"winsymlinks", {func: set_winsymlinks}, isfunc, NULL, {{0}, {0}}},
       {"disable_pcon", {&disable_pcon}, setbool, NULL, {{false}, {true}}},
   -   {"enable_pcon", {&disable_pcon}, setnegbool, NULL, {{true}, {false}}},
    +  {"winjitdebug", {&winjitdebug}, setbool, NULL, {{false}, {true}}},
       {NULL, {0}, setdword, 0, {{0}, {0}}}
     };
   @@ winsup/cygwin/environ.cc: static struct parse_thing
    
     ## winsup/cygwin/globals.cc ##
    @@ winsup/cygwin/globals.cc: bool reset_com;
   - bool wincmdln = true;
   - winsym_t allow_winsymlinks = WSYM_deepcopy;
   + bool wincmdln;
   + winsym_t allow_winsymlinks = WSYM_default;
     bool disable_pcon;
    +bool winjitdebug = false;
     
   ``````

</details>

<details><summary>"dumper: avoid linker problem when `libbfd` depends on `libsframe`" (done _very_ differently)</summary>

* 1:  06562dd490 ! 1:  1387ea9f98 dumper: avoid linker problem when `libbfd` depends on `libsframe`

   ``````diff
   @@
     ## Metadata ##
   -Author: Johannes Schindelin <johannes.schindelin@gmx.de>
   +Author: Jon Turney <jon.turney@dronecode.org.uk>
    
     ## Commit message ##
   -    dumper: avoid linker problem when `libbfd` depends on `libsframe`
   +    Cygwin: dumper: also link with libzstd, as libbfd may require it
    
   -    A recent binutils version introduced `libsframe` and made it a
   -    dependency of `libbfd`. This caused a linker problem in the MSYS2
   -    project, and once Cygwin upgrades to that binutils version it would
   -    cause the same problems there.
   +    Also allow that linkage to be dynamic, as libzstd-devel doesn't
   +    currently provide a static library.
    
   -    Let's preemptively detect the presence of `libsframe` and if detected,
   -    link to it in addition to `libbfd`.
   + ## .appveyor.yml ##
   +@@ .appveyor.yml: patch,\
   + cocom,\
   + gettext-devel,\
   + libiconv-devel,\
   ++libzstd-devel,\
   + zlib-devel,\
   + %PKGARCH%-gcc-core,\
   + %PKGARCH%-gcc-g++,\
    
   -    Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>
   + ## .github/workflows/cygwin.yml ##
   +@@ .github/workflows/cygwin.yml: jobs:
   +           gettext-devel,
   +           libiconv,
   +           libiconv-devel,
   ++          libzstd-devel,
   +           make,
   +           mingw64-${{ matrix.pkgarch }}-gcc-g++,
   +           mingw64-${{ matrix.pkgarch }}-zlib,
    
     ## winsup/configure.ac ##
   -@@ winsup/configure.ac: AC_CHECK_LIB([sframe], [sframe_decode], [BFD_LIBS="${BFD_LIBS} -lsframe"])
   - AC_CHECK_LIB([zstd], [ZSTD_isError], [BFD_LIBS="${BFD_LIBS} -lzstd"])
   - AC_SUBST([BFD_LIBS])
   +@@ winsup/configure.ac: AC_ARG_ENABLE([dumper],
   + 
   + AM_CONDITIONAL(BUILD_DUMPER, [test "x$build_dumper" = "xyes"])
   + 
   +-AC_CHECK_LIB([sframe], [sframe_decode],
   +-	     AC_MSG_NOTICE([Detected libsframe; Assuming that libbfd depends on it]), [true])
   +-
   +-AM_CONDITIONAL(HAVE_LIBSFRAME, [test "x$ac_cv_lib_sframe_sframe_decode" = "xyes"])
   ++# libbfd.a doesn't have a pkgconfig file, so we guess what it's dependencies
   ++# are, based on what's present in the build environment
   ++BFD_LIBS="-lintl -liconv -liberty -lz"
   ++AC_CHECK_LIB([sframe], [sframe_decode], [BFD_LIBS="${BFD_LIBS} -lsframe"])
   ++AC_CHECK_LIB([zstd], [ZSTD_isError], [BFD_LIBS="${BFD_LIBS} -lzstd"])
   ++AC_SUBST([BFD_LIBS])
     
   -+AC_CHECK_LIB([sframe], [sframe_decode],
   -+	     AC_MSG_NOTICE([Detected libsframe; Assuming that libbfd depends on it]), [true])
   -+
   -+AM_CONDITIONAL(HAVE_LIBSFRAME, [test "x$ac_cv_lib_sframe_sframe_decode" = "xyes"])
   -+
     AC_CONFIG_FILES([
         Makefile
   -     cygwin/Makefile
   +
   + ## winsup/doc/faq-programming.xml ##
   +@@ winsup/doc/faq-programming.xml: installed; you at least need <literal>gcc-g++</literal>,
   + 
   + <para>
   + Additionally, building the <code>dumper</code> utility requires
   +-<literal>gettext-devel</literal>, <literal>libiconv-devel</literal>
   ++<literal>gettext-devel</literal>, <literal>libiconv-devel</literal>, <literal>libzstd-devel</literal> and
   + <literal>zlib-devel</literal>.  Building this program can be disabled with the
   + <literal>--disable-dumper</literal> option to <literal>configure</literal>.
   + </para>
    
     ## winsup/utils/Makefile.am ##
   +@@ winsup/utils/Makefile.am: LDADD = -lnetapi32
   + cygpath_CXXFLAGS = -fno-threadsafe-statics $(AM_CXXFLAGS)
   + cygpath_LDADD = $(LDADD) -luserenv -lntdll
   + dumper_CXXFLAGS = -I$(top_srcdir)/../include $(AM_CXXFLAGS)
   +-dumper_LDADD = $(LDADD) -lpsapi -lbfd -lintl -liconv -liberty -lz -lntdll
   ++dumper_LDADD = $(LDADD) -lpsapi -lntdll -lbfd @BFD_LIBS@
   ++dumper_LDFLAGS =
   + ldd_LDADD = $(LDADD) -lpsapi -lntdll
   + mount_CXXFLAGS = -DFSTAB_ONLY $(AM_CXXFLAGS)
   + minidumper_LDADD = $(LDADD) -ldbghelp
    @@ winsup/utils/Makefile.am: profiler_LDADD = $(LDADD) -lntdll
     cygps_LDADD = $(LDADD) -lpsapi -lntdll
     newgrp_LDADD = $(LDADD) -luserenv
     
   -+if HAVE_LIBSFRAME
   -+dumper_LDADD += -lsframe
   -+endif
   -+
   +-if HAVE_LIBSFRAME
   +-dumper_LDADD += -lsframe
   +-endif
   +-
     if CROSS_BOOTSTRAP
     SUBDIRS = mingw
     endif
   ``````

</details>

<details><summary>"Cygwin: console: Fix exit code for non-cygwin process." (was a backport)</summary>

* 1:  2ba3c86744 ! 1:  aa73e11524 Cygwin: console: Fix exit code for non-cygwin process.

   ``````diff
   @@ Commit message
        Fixes: 3721a756b0d8 ("Cygwin: console: Make the console accessible from other terminals.")
        Reported-by: Johannes Schindelin <Johannes.Schindelin@gmx.de>
        Signed-off-by: Takashi Yano <takashi.yano@nifty.ne.jp>
   -    Backported-from: aa73e11524 (Cygwin: console: Fix exit code for non-cygwin process., 2024-02-02)
   -    Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>
    
     ## winsup/cygwin/fhandler/console.cc ##
    @@ winsup/cygwin/fhandler/console.cc: fhandler_console::need_console_handler ()
   ``````

</details>

<details><summary>"Work around fragile `#include` in binutils" (done independently, and very differently)</summary>

* 1:  ef393717bb ! 1:  a85f1c3d0f Work around fragile `#include` in binutils

   ``````diff
   @@
     ## Metadata ##
   -Author: Johannes Schindelin <johannes.schindelin@gmx.de>
   +Author: Corinna Vinschen <corinna@vinschen.de>
    
     ## Commit message ##
   -    Work around fragile `#include` in binutils
   +    include/ansidecl.h: import from binutils-gdb
    
   -    The `bfd.h` header file that is included in `binutils` has the line
   -    `#include "ansidecl.h"`, which is fragile because it prefers Cygwin's
   -    `include/ansidecl.h` (as opposed to `#include <ansidecl.h>`, which would
   -    only look in the system include paths).
   +    Import include/ansidecl.h version from 2024-01-04,
   +    binutils-gdb commit fd67aa1129fd.
    
   -    This matters because as of v2.42, `bfd.h` also makes use of the
   -    `ATTRIBUTE_WARN_UNUSED_RESULT` macro.
   -
   -    So let's just copy that macro (and while at it, the other `ATTRIBUTE_*`
   -    macros) from binutils' `ansidecl.h` file, to avoid compile errors while
   -    compiling `dumper.o` that look like this:
   -
   -      /usr/include/bfd.h:2770:1: error: expected initializer before ΓÇÿATTRIBUTE_WARN_UNUSED_RESULTΓÇÖ
   -       2770 | ATTRIBUTE_WARN_UNUSED_RESULT;
   -            | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
   -
   -    Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>
   +    Signed-off-by: Corinna Vinschen <corinna@vinschen.de>
   +    (cherry picked from commit 10c8c1cf4f94ed42c59015d7e972269724c451bf)
    
     ## include/ansidecl.h ##
   +@@
   +-/* ANSI and traditional C compatability macros
   +-   Copyright (C) 1991-2015 Free Software Foundation, Inc.
   ++/* Compiler compatibility macros
   ++   Copyright (C) 1991-2024 Free Software Foundation, Inc.
   +    This file is part of the GNU C Library.
   + 
   + This program is free software; you can redistribute it and/or modify
   +@@ include/ansidecl.h: You should have received a copy of the GNU General Public License
   + along with this program; if not, write to the Free Software
   + Foundation, Inc., 51 Franklin Street - Fifth Floor, Boston, MA 02110-1301, USA.  */
   + 
   +-/* ANSI and traditional C compatibility macros
   +-
   +-   ANSI C is assumed if __STDC__ is #defined.
   +-
   +-   Macro		ANSI C definition	Traditional C definition
   +-   -----		---- - ----------	----------- - ----------
   +-   PTR			`void *'		`char *'
   +-   const		not defined		`'
   +-   volatile		not defined		`'
   +-   signed		not defined		`'
   +-
   +-   For ease of writing code which uses GCC extensions but needs to be
   ++/* For ease of writing code which uses GCC extensions but needs to be
   +    portable to other compilers, we provide the GCC_VERSION macro that
   +    simplifies testing __GNUC__ and __GNUC_MINOR__ together, and various
   +    wrappers around __attribute__.  Also, __extension__ will be #defined
   +@@ include/ansidecl.h: So instead we use the macro below and test it against specific values.  */
   + #define GCC_VERSION (__GNUC__ * 1000 + __GNUC_MINOR__)
   + #endif /* GCC_VERSION */
   + 
   +-#if defined (__STDC__) || defined(__cplusplus) || defined (_AIX) || (defined (__mips) && defined (_SYSTYPE_SVR4)) || defined(_WIN32)
   +-/* All known AIX compilers implement these things (but don't always
   +-   define __STDC__).  The RISC/OS MIPS compiler defines these things
   +-   in SVR4 mode, but does not define __STDC__.  */
   +-/* eraxxon@alumni.rice.edu: The Compaq C++ compiler, unlike many other
   +-   C++ compilers, does not define __STDC__, though it acts as if this
   +-   was so. (Verified versions: 5.7, 6.2, 6.3, 6.5) */
   +-
   +-#define PTR		void *
   +-
   +-#undef const
   +-#undef volatile
   +-#undef signed
   +-
   + /* inline requires special treatment; it's in C99, and GCC >=2.7 supports
   +    it too, but it's not in C89.  */
   + #undef inline
   +-#if __STDC_VERSION__ >= 199901L || defined(__cplusplus) || (defined(__SUNPRO_C) && defined(__C99FEATURES__))
   ++#if (!defined(__cplusplus) && __STDC_VERSION__ >= 199901L) || defined(__cplusplus) || (defined(__SUNPRO_C) && defined(__C99FEATURES__))
   + /* it's a keyword */
   + #else
   + # if GCC_VERSION >= 2007
   +@@ include/ansidecl.h: So instead we use the macro below and test it against specific values.  */
   + # endif
   + #endif
   + 
   +-#else	/* Not ANSI C.  */
   +-
   +-#define PTR		char *
   +-
   +-/* some systems define these in header files for non-ansi mode */
   +-#undef const
   +-#undef volatile
   +-#undef signed
   +-#undef inline
   +-#define const
   +-#define volatile
   +-#define signed
   +-#define inline
   +-
   +-#endif	/* ANSI C.  */
   +-
   + /* Define macros for some gcc attributes.  This permits us to use the
   +    macros freely, and know that they will come into play for the
   +    version of gcc in which they are supported.  */
   +@@ include/ansidecl.h: So instead we use the macro below and test it against specific values.  */
   + # endif /* GNUC >= 3.0 */
   + #endif /* ATTRIBUTE_ALIGNED_ALIGNOF */
   + 
   +-/* Useful for structures whose layout must much some binary specification
   ++/* Useful for structures whose layout must match some binary specification
   +    regardless of the alignment and padding qualities of the compiler.  */
   + #ifndef ATTRIBUTE_PACKED
   + # define ATTRIBUTE_PACKED __attribute__ ((packed))
    @@ include/ansidecl.h: So instead we use the macro below and test it against specific values.  */
     # endif /* GNUC >= 4.9 */
     #endif /* ATTRIBUTE_NO_SANITIZE_UNDEFINED */
   @@ include/ansidecl.h: So instead we use the macro below and test it against specif
     /* We use __extension__ in some places to suppress -pedantic warnings
        about GCC extensions.  This feature didn't work properly before
        gcc 2.8.  */
   +@@ include/ansidecl.h: So instead we use the macro below and test it against specific values.  */
   + #define ENUM_BITFIELD(TYPE) unsigned int
   + #endif
   + 
   +-    /* This is used to mark a class or virtual function as final.  */
   +-#if __cplusplus >= 201103L
   +-#define GCC_FINAL final
   +-#elif GCC_VERSION >= 4007
   +-#define GCC_FINAL __final
   ++#if defined(__cplusplus) && __cpp_constexpr >= 200704
   ++#define CONSTEXPR constexpr
   + #else
   +-#define GCC_FINAL
   ++#define CONSTEXPR
   + #endif
   + 
   ++/* A macro to disable the copy constructor and assignment operator.
   ++   When building with C++11 and above, the methods are explicitly
   ++   deleted, causing a compile-time error if something tries to copy.
   ++   For C++03, this just declares the methods, causing a link-time
   ++   error if the methods end up called (assuming you don't
   ++   define them).  For C++03, for best results, place the macro
   ++   under the private: access specifier, like this,
   ++
   ++   class name_lookup
   ++   {
   ++     private:
   ++       DISABLE_COPY_AND_ASSIGN (name_lookup);
   ++   };
   ++
   ++   so that most attempts at copy are caught at compile-time.  */
   ++
   ++#if defined(__cplusplus) && __cplusplus >= 201103
   ++#define DISABLE_COPY_AND_ASSIGN(TYPE)		\
   ++  TYPE (const TYPE&) = delete;			\
   ++  void operator= (const TYPE &) = delete
   ++  #else
   ++#define DISABLE_COPY_AND_ASSIGN(TYPE)		\
   ++  TYPE (const TYPE&);				\
   ++  void operator= (const TYPE &)
   ++#endif /* __cplusplus >= 201103 */
   ++
   + #ifdef __cplusplus
   + }
   + #endif
   ``````

</details>

<details><summary>"Cygwin: console: Avoid slipping past disable_master_thread check." (was a backport)</summary>

* 1:  ec35e8a470 = 1:  9bcfd06045 Cygwin: console: Avoid slipping past disable_master_thread check.

</details>

<details><summary>"Cygwin: pty: Fix handle leak in master process." (was a backport)</summary>

   ``````

* 1:  c73fabb33a ! 1:  a6ac7b4138 Cygwin: pty: Fix handle leak in master process.

   ``````diff
   @@ Commit message
        Fixes: 29431fcb5b14 ("Cygwin: pty: Inherit typeahead data between two input pipes.")
        Reported-by: Hakkin Lain
        Signed-off-by: Takashi Yano <takashi.yano@nifty.ne.jp>
   -    Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>
    
     ## winsup/cygwin/fhandler/pty.cc ##
    @@ winsup/cygwin/fhandler/pty.cc: fhandler_pty_slave::transfer_input (tty::xfer_dir dir, HANDLE from, tty *ttyp,
   @@ winsup/cygwin/fhandler/pty.cc: fhandler_pty_slave::transfer_input (tty::xfer_dir
     
       /* Fix input_available_event which indicates availability in cyg pipe. */
       if (dir == tty::to_nat) /* all data is transfered to nat pipe,
   +
   + ## winsup/cygwin/release/3.5.1 ##
   +@@ winsup/cygwin/release/3.5.1: Fixes:
   +   error mode is now possible by using the new CYGWIN environment variable
   +   option "winjitdebug".
   +   Addresses: https://cygwin.com/pipermail/cygwin/2024-February/255305.html
   ++
   ++- Fix handle leak in pty master which occurs when non-cygwin process
   ++  is started in pty.
   ++  Addresses: https://github.com/msys2/msys2-runtime/issues/198
   ``````

</details>

<details><summary>"Cygwin: pty: Fix potential handle leak regarding CallNamedPipe()." (was a backport)</summary>

* 1:  41499b18c4 ! 1:  73cd80c976 Cygwin: pty: Fix potential handle leak regarding CallNamedPipe().

   ``````diff
   @@ Commit message
        they were not. This causes handle leak potentially.
    
        Signed-off-by: Takashi Yano <takashi.yano@nifty.ne.jp>
   -    Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>
    
     ## winsup/cygwin/fhandler/pty.cc ##
    @@ winsup/cygwin/fhandler/pty.cc: fhandler_pty_slave::open (int flags, mode_t)
   ``````

</details>

<details><summary>"Cygwin: console: Make VMIN and VTIME work." (was a backport)</summary>

   ``````

* 1:  51aae37287 ! 1:  02f7f6543a Cygwin: console: Make VMIN and VTIME work.

   ``````diff
   @@ Commit message
        Previously, VMIN and VTIME did not work at all. This patch fixes that.
    
        Signed-off-by: Takashi Yano <takashi.yano@nifty.ne.jp>
   -    Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>
    
     ## winsup/cygwin/fhandler/console.cc ##
    @@ winsup/cygwin/fhandler/console.cc: fhandler_console::read (void *pv, size_t& buflen)
   @@ winsup/cygwin/fhandler/console.cc: wait_retry:
     #undef buf
     
       buflen = copied_chars;
   +
   + ## winsup/cygwin/release/3.5.1 ##
   +@@ winsup/cygwin/release/3.5.1: Fixes:
   + - Fix handle leak in pty master which occurs when non-cygwin process
   +   is started in pty.
   +   Addresses: https://github.com/msys2/msys2-runtime/issues/198
   ++
   ++- Fix the problem that VMIN and VTIME does not work at all in console.
   ``````

</details>

<details><summary>"Cygwin: console: Fix a problem that minor ID is incorrect in ConEmu." (was a backport)</summary>

* 1:  711907eb6c ! 1:  0795afd68e Cygwin: console: Fix a problem that minor ID is incorrect in ConEmu.

   ``````diff
   @@ Commit message
        not enumerated by EnumWindows(). This patch fixes the issue.
    
        Signed-off-by: Takashi Yano <takashi.yano@nifty.ne.jp>
   -    Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>
    
     ## winsup/cygwin/autoload.cc ##
    @@ winsup/cygwin/autoload.cc: LoadDLLfunc (DefWindowProcW, user32)
   ``````

</details>

### CODE REVIEW

**Comment by dscho** [comment]
I validated this manually a bit and also [executed Git's test suite on it](https://github.com/dscho/git-for-windows-automation/actions/runs/8067353718/job/22037550864). I guess we should also add a CI workflow that checks out https://github.com/msys2/msys2-tests and runs those tests?

**Comment by lazka** [comment]
lgtm

> I validated this manually a bit and also [executed Git's test suite on it](https://github.com/dscho/git-for-windows-automation/actions/runs/8067353718/job/22037550864). I guess we should also add a CI workflow that checks out https://github.com/msys2/msys2-tests and runs those tests?

yes, see #135

**Comment by lazka** [comment]
ah, I wasn't reading your question properly, I though you were talking about the internal test suite, sorry.

Adding some integration tests would certainly help I guess.

**Comment by dscho** [comment]
> Adding some integration tests would certainly help I guess.

Yes, I was actually thinking specifically of the `path_conv` tests in `msys2-tests`.

But you have a good point: Now that Cygwin is taking care of their testsuite, we would be fools not to follow suit and make it work for MSYS2, too. Confidence building and some such...

I am just unsure whether we should fold this into the rebase to v3.5.1. It might make more sense to get it to work on `msys2-3.4.10`, and hold off updating to v3.5.1 until that time.

**Comment by dscho** [comment]
> It might make more sense to get it to work on `msys2-3.4.10`

What am I thinking! Cygwin's test suite isn't working on v3.4.*, is it?

**Comment by lazka** [comment]
> What am I thinking! Cygwin's test suite isn't working on v3.4.*, is it?

yeah, it was broken in 3.4

With CPython our strategy is to just skip broken tests in CI, so we at least detect regressions in the working ones. Which would be a good start imho, without requiring too much work.

**Comment by dscho** [comment]
> With CPython our strategy is to just skip broken tests in CI, so we at least detect regressions in the working ones. Which would be a good start imho, without requiring too much work.

That makes sense to me!

However, it makes even more sense to me to merge this here PR first, then add the `msys2-runtime-3.5` package in `MSYS2-packages` so tire kickers can have a go at it, and then add a PR to run the tests in CI (disabling whatever is broken in the initial version).

**Pull request merged**
