### PR TITLE
backport recent console patches

### PR DESCRIPTION
**Pull request by jeremyd2019**
This seems to solve the same issue that git-for-windows/msys2-runtime@1d0701d attempted to solve, but without the side effects (git-for-windows/git#3657, #83).

### CODE REVIEW

**Comment by dscho** [comment]
Thank you! I integrated these patches via https://github.com/git-for-windows/msys2-runtime/pull/40#commits-pushed-c8568e0, let's hope that the Console problems settle down some (my expectations for that are low, though).

**Comment by dscho** [comment]
I can confirm that this indeed fixes https://github.com/GitCredentialManager/git-credential-manager/issues/576, too.

**Review by dscho — APPROVED** [review]

**Comment by jeremyd2019** [comment]
I backported the commits to git-for-windows/msys2-runtime main and confirmed that it fixes #83 and git-for-windows/git#3657 there (though your PR updating to 3.3.4 makes more sense, because there were merge issues backporting to 3.3.3 resulting in my dropping some fixes that depended on other fixes that weren't in 3.3.3).

**Comment by jeremyd2019** [comment]
One thing to look out for - I think the proliferation of GenerateConsoleCtrlEvent calls in these patches and in some already in 3.3.4 may degrade the custom Ctrl-C handling code that was added to msys2-runtime.

**Pull request merged**
