### PR TITLE
Upgrade to 3.1.7

### PR DESCRIPTION
**Pull request by lazka**
```
$ git range-diff cygwin-3_1_6-release..msys2-3_1_6-release cygwin-3_1_7-release..upgrade-3.1.7
  1:  47b4b9e03 =  1:  d4ab82f33 Add MSYS2 triplet
 2:  27d4b88a7 =  2:  8f7df4277 Rename dll from cygwin to msys
 3:  91990dabd !  3:  41966a9e4 Add functionality for converting UNIX paths in arguments and environment variables to Windows form for native Win32 applications.
    @@ winsup/cygwin/msys2_path_conv.cc (new)
     +
     +        for (; *it != '\0' && it != end; ++it) {
     +            switch(*it) {
    -+                case ':': {char ch = *(it + 1); if (ch == '/' || ch == ':' || ch == '.') return POSIX_PATH_LIST;}
    ++                case ':': {char ch = *(it + 1); if (ch == '/' || ch == ':' || ch == '.') return POSIX_PATH_LIST;} return WINDOWS_PATH_LIST;
     +                case ';': return WINDOWS_PATH_LIST;
     +            }
     +        }
 4:  709e97e0c =  4:  2ea59c6ab Add functionality for changing OS name via MSYSTEM environment variables.
 5:  ce142c668 =  5:  195b78e0f - Move root to /usr. - Change sorting mount points. - By default mount without ACLs. - Can read /etc/fstab with short mount point format.
 6:  b059d9b75 =  6:  226d31376 Do not create cygwin symlinks. Instead use deep copy of files/folders.
 7:  c7269ed9c =  7:  27407cc83 Automatically rewrite TERM=msys to TERM=cygwin With MSys1, it was necessary to set the TERM variable to "msys". To allow for a smooth transition from MSys1 to MSys2, let's simply handle TERM=msys as if the user had not specified TERM at all and wanted us to use our preferred TERM value.
 8:  3a914a11d =  8:  bd5faccd4 Do not convert environment for strace
 9:  4e28c7cb8 =  9:  9de87acc0 Special case for converting root directory to have training slash
10:  7dec89da7 = 10:  a2eb0bde2 dcrt0.cc: Untangle allow_glob from winshell
11:  b898ee64a = 11:  134ed7702 dcrt0.cc (globify): Don't quote literal strings differently when dos_spec
12:  f7df18ddf = 12:  4e94dde16 strace.cc: Don't set MSYS=noglob
13:  d7a64e150 = 13:  2cf20a4c6 Add debugging for build_argv
14:  cf112c877 = 14:  f3fb95985 Add debugging for strace make_command_line
15:  910547eb4 = 15:  c3fc7d808 environ.cc: New facility/environment variable MSYS2_ENV_CONV_EXCL
16:  29271c441 = 16:  2e3556522 Fix native symbolic link spawn passing wrong arg0
17:  ddaba6837 = 17:  ec95a41b0 QueryUnbiasedInterruptTime must be load from kernel32.dll
18:  69c24dc4b = 18:  5dc28ff14 fixup! Do not create cygwin symlinks. Instead use deep copy of files/folders.
19:  ed39bf116 = 19:  d1d44a3c1 strace --quiet: be *really* quiet
20:  a74d515dc = 20:  a3ae81bbc Default to `disable_pcon`
21:  244c7a80d = 21:  d54082f4a Introduce the `enable_pcon` value for `MSYS`
22:  ffdf71dab ! 22:  91ad0d65f Don't create WSL symlinks for MSYS2
    @@ winsup/cygwin/path.cc: symlink_worker (const char *oldpath, path_conv &win32_new
      	  /* Otherwise, fall back to default symlink type. */
      	  wsym_type = WSYM_sysfile;
     +#ifndef __MSYS__
    - 	  /*FALLTHRU*/
    + 	  fallthrough;
      	case WSYM_sysfile:
      	  if (win32_newpath.fs_flags () & FILE_SUPPORTS_REPARSE_POINTS)
     @@ winsup/cygwin/path.cc: symlink_worker (const char *oldpath, path_conv &win32_newpath, bool isdevice)
23:  c5e972d5a = 23:  9c8d9a68d popen: call /usr/bin/sh instead of /bin/sh
24:  1de7bb9fd = 24:  df6f7f098 CI: add a GHA for doing a basic build test
25:  4bbf0abde = 25:  55d4c6dcb Set up a GitHub Action to keep in sync with Cygwin
26:  c41b1ed54 <  -:  --------- recursiveCopy: Always close the used handle with FindClose()
27:  7b8896963 <  -:  --------- fixup! Add functionality for converting UNIX paths in arguments and environment variables to Windows form for native Win32 applications.
28:  5f10a64eb <  -:  --------- Expose full command-lines to other Win32 processes by default
```

### CODE REVIEW

**Comment by dscho** [comment]
@lazka to fix https://github.com/msys2/msys2-runtime/pull/11/checks?check_run_id=1018022835#step:4:2165, I believe that you need to add an explicit `/* fallthrough */` comment, just like https://github.com/msys2/msys2-runtime/blob/a93a85a1ff3ca937dabb1d985381b27836ce1bfc/newlib/libc/stdio/vfprintf.c#L2283 (the `:` case in the path list is clearly intended to replace `:` by `;` and then fall through to the `;` case).

**Comment by dscho** [comment]
> I believe that you need to add an explicit `/* fallthrough *`

I was wrong. That part of the code is compiled using `-Wimplicit-fallthrough=5` (i.e. "no fall-through, no exceptions!").

**Comment by dscho** [comment]
Here's the diff that seems to fix the build for me:

```diff
diff --git a/winsup/cygwin/msys2_path_conv.cc b/winsup/cygwin/msys2_path_conv.cc
index a989734a7..f9dcda5d6 100644
--- a/winsup/cygwin/msys2_path_conv.cc
+++ b/winsup/cygwin/msys2_path_conv.cc
@@ -395,7 +395,7 @@ path_type find_path_start_and_type(const char** src, int recurse, const char* en
 
         for (; *it != '\0' && it != end; ++it) {
             switch(*it) {
-                case ':': {char ch = *(it + 1); if (ch == '/' || ch == ':' || ch == '.') return POSIX_PATH_LIST;}
+                case ':': {char ch = *(it + 1); if (ch == '/' || ch == ':' || ch == '.') return POSIX_PATH_LIST;} return WINDOWS_PATH_LIST;
                 case ';': return WINDOWS_PATH_LIST;
             }
         }
```

**Comment by dscho** [comment]
And this is the commit that needs to be fixed up with that diff: 8ee205fe2bdca983fb0dfe9bf12defae4848e953

**Comment by jeremyd2019** [comment]
Am I missing something or did the last couple of patches to expose the command line to win32 get dropped?  Was that change applied upstream?

**Comment by dscho** [comment]
> 
> 
> Am I missing something or did the last couple of patches to expose the command line to win32 get dropped? Was that change applied upstream?

Thanks for pointing that out. I opened #12 to fix that.

**Comment by lazka** [comment]
oops :D

**Pull request merged**
